install.packages("dplyr",dependencies = TRUE)
install.packages("ggplot2",dependencies = TRUE)
install.packages("gridExtra",dependencies = TRUE)
install.packages("ReporteRs",dependencies = TRUE)
install.packages("lazyeval",dependencies = TRUE)

# install.packages(c("devtools","RJSONIO", "knitr", "shiny", "httpuv"))
# library(devtools)
# install_github("mages/googleVis")
# install.packages("igraph", dependencies = TRUE)
# install.packages('base64enc')
# devtools::install_github( 'rCharts','ramnathv',ref='dev' )